# Generated by Django 5.0.4 on 2024-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytenews', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
