# Generated by Django 5.0.4 on 2024-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytenews', '0003_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
